kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-storage

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
  volumeMode: Filesystem
