apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-pods
  labels:
    k8s-app: prometheus
    team: opendatahub
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /prometheus
      port: metrics
  selector:
    matchLabels:
      team: opendatahub
