apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: data
  labels:
    strimzi.io/cluster: odh-message-bus
  namespace: {{  .Values.namespace }}
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 3
  topicName: data